function kinematics_foot = foot_Func(x,y,r,th_f,l_f,thk_f,tha_f,th_b,l_b,thk_b,tha_b,dx,dy,dr,dth_f,dl_f,dthk_f,dtha_f,dth_b,dl_b,dthk_b,dtha_b)
%foot_Func
%    KINEMATICS_FOOT = foot_Func(X,Y,R,TH_F,L_F,THK_F,THA_F,TH_B,L_B,THK_B,THA_B,DX,DY,DR,DTH_F,DL_F,DTHK_F,DTHA_F,DTH_B,DL_B,DTHK_B,DTHA_B)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    19-Mar-2025 08:54:47

t2 = cos(r);
t3 = cos(th_b);
t4 = cos(th_f);
t5 = cos(thk_b);
t6 = cos(thk_f);
t7 = sin(r);
t8 = sin(th_b);
t9 = sin(th_f);
t10 = sin(thk_b);
t11 = sin(thk_f);
mt1 = [t2.*(1.59e+2./5.0e+2)-t4.*(1.21e+2./5.0e+2)+t6.*(1.17e+2./5.0e+2)+x,t7.*(1.59e+2./5.0e+2)-t9.*(1.21e+2./5.0e+2)-t11.*(1.17e+2./5.0e+2)+y,dx-dr.*t7.*(1.59e+2./5.0e+2)+dth_f.*t9.*(1.21e+2./5.0e+2)-dthk_f.*t11.*(1.17e+2./5.0e+2),dy+dr.*t2.*(1.59e+2./5.0e+2)-dth_f.*t4.*(1.21e+2./5.0e+2)-dthk_f.*t6.*(1.17e+2./5.0e+2),t2.*(-9.9e+1./5.0e+2)+t3.*(1.21e+2./5.0e+2)-t5.*(1.17e+2./5.0e+2)+x,t7.*(-9.9e+1./5.0e+2)-t8.*(1.21e+2./5.0e+2)-t10.*(1.17e+2./5.0e+2)+y];
mt2 = [dx+dr.*t7.*(9.9e+1./5.0e+2)-dth_b.*t8.*(1.21e+2./5.0e+2)+dthk_b.*t10.*(1.17e+2./5.0e+2),dy-dr.*t2.*(9.9e+1./5.0e+2)-dth_b.*t3.*(1.21e+2./5.0e+2)-dthk_b.*t5.*(1.17e+2./5.0e+2)];
kinematics_foot = reshape([mt1,mt2],4,2);
end
