function dth_function = dth_calc(phi,l,dphi,dl)
%DTH_CALC
%    DTH_FUNCTION = DTH_CALC(PHI,L,DPHI,DL)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    04-Nov-2025 10:09:02

t2 = l+2.7e+1./1.25e+2;
t4 = l.*7.161773274254708e+1;
t3 = t2.^2;
t7 = t4+1.546943027239017e+1;
t5 = t3.*3.580886637127354e+1;
t6 = -t5;
t9 = t5-2.26516146004765;
t8 = t6+2.26516146004765;
t11 = t9.^2;
t10 = acos(t8);
t12 = -t11;
t13 = t12+1.0;
t15 = t10+1.557529807512923e-1;
t14 = 1.0./sqrt(t13);
t16 = cos(t15);
t17 = sin(t15);
t18 = t17.^2;
t19 = t16.*1.13256e-1;
t20 = -t19;
t21 = t20+1.1332e-1;
dth_function = dphi-dl.*1.0./sqrt((t18.*5.4756e-2)./(t19-1.1332e-1)+1.0).*(t7.*t14.*t16.*1.0./sqrt(t21).*(1.17e+2./5.0e+2)-t7.*t14.*t18.*1.0./t21.^(3.0./2.0).*1.3250952e-2);
end
