function dthk = dthk_calc(th,l,dth,dl)
%DTHK_CALC
%    DTHK = DTHK_CALC(TH,L,DTH,DL)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    04-Nov-2025 10:09:00

dthk = -dth+dl.*(l.*7.161773274254708e+1+1.546943027239017e+1).*1.0./sqrt(-((l+2.7e+1./1.25e+2).^2.*3.580886637127354e+1-2.26516146004765).^2+1.0);
end
