function kinematics_foot = foot_Func(x,y,th,l,thk,tha,dx,dy,dth,dl,dthk,dtha)
%foot_Func
%    KINEMATICS_FOOT = foot_Func(X,Y,TH,L,THK,THA,DX,DY,DTH,DL,DTHK,DTHA)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    04-Nov-2025 10:09:00

t2 = cos(th);
t3 = cos(thk);
t4 = sin(th);
t5 = sin(thk);
kinematics_foot = [t2.*(1.21e+2./5.0e+2)-t3.*(1.17e+2./5.0e+2)+x-1.2764e-1;t4.*(-1.21e+2./5.0e+2)-t5.*(1.17e+2./5.0e+2)+y-1.0./5.0e+1;dx-dth.*t4.*(1.21e+2./5.0e+2)+dthk.*t5.*(1.17e+2./5.0e+2);dy-dth.*t2.*(1.21e+2./5.0e+2)-dthk.*t3.*(1.17e+2./5.0e+2)];
end
