function tha = tha_calc(th,l)
%THA_CALC
%    THA = THA_CALC(TH,L)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    04-Nov-2025 10:09:00

tha = th-pi./2.0+acos(((l+2.7e+1./1.25e+2).^2+5.6759e-2)./(l.*4.899306073312832e-1+1.058250111835572e-1))+1.415043346043604;
end
