function thk = thk_calc(th,l)
%THK_CALC
%    THK = THK_CALC(TH,L)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    04-Nov-2025 10:09:00

thk = -th+acos((l+2.7e+1./1.25e+2).^2.*(-3.580886637127354e+1)+2.26516146004765)+1.557529807512923e-1;
end
