function C = C_func(x,y,r,th_f,l_f,thk_f,tha_f,th_b,l_b,thk_b,tha_b,dx,dy,dr,dth_f,dl_f,dthk_f,dtha_f,dth_b,dl_b,dthk_b,dtha_b)
%C_func
%    C = C_func(X,Y,R,TH_F,L_F,THK_F,THA_F,TH_B,L_B,THK_B,THA_B,DX,DY,DR,DTH_F,DL_F,DTHK_F,DTHA_F,DTH_B,DL_B,DTHK_B,DTHA_B)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    19-Mar-2025 08:54:46

t2 = cos(th_b);
t3 = cos(th_f);
t4 = cos(tha_b);
t5 = cos(tha_f);
t6 = sin(th_b);
t7 = sin(th_f);
t8 = sin(tha_b);
t9 = sin(tha_f);
t10 = r+th_b;
t11 = r+tha_b;
t12 = r+thk_f;
t13 = th_b+thk_b;
t14 = th_f+thk_f;
t15 = dr.^2;
t16 = dth_b.^2;
t17 = dth_f.^2;
t18 = dtha_b.^2;
t19 = dtha_f.^2;
t20 = dthk_b.^2;
t21 = dthk_f.^2;
t29 = -th_f;
t30 = -tha_b;
t31 = -tha_f;
t32 = -thk_b;
t22 = cos(t10);
t23 = cos(t11);
t24 = sin(t10);
t25 = sin(t11);
t26 = sin(t12);
t27 = sin(t13);
t28 = sin(t14);
t33 = r+t29;
t34 = r+t31;
t35 = r+t32;
t36 = t30+th_b;
t37 = t31+th_f;
t38 = cos(t33);
t39 = cos(t34);
t40 = cos(t36);
t41 = cos(t37);
t42 = sin(t33);
t43 = sin(t34);
t44 = sin(t35);
t45 = sin(t36);
t46 = sin(t37);
et1 = t2.*t16.*(-8.46484212e-2)+t3.*t17.*8.46484212e-2-t4.*t18.*6.658716e-2+t6.*t16.*2.6904e-2+t5.*t19.*6.658716e-2-t7.*t17.*2.6904e-2-t15.*cos(r).*5.201963354483954e-1+t20.*cos(thk_b).*5.949652e-2;
et2 = t21.*cos(thk_f).*(-1.924852e-2)-dl_b.*dtha_b.*t8.*(4.6e+1./1.25e+2)+dl_f.*dtha_f.*t9.*(4.6e+1./1.25e+2)-l_b.*t4.*t18.*(2.3e+1./1.25e+2)+l_f.*t5.*t19.*(2.3e+1./1.25e+2);
et3 = t2.*t16.*2.6904e-2+t3.*t17.*2.6904e-2+t6.*t16.*8.46484212e-2+t7.*t17.*8.46484212e-2+t8.*t18.*6.658716e-2+t9.*t19.*6.658716e-2-t15.*sin(r).*5.201963354483954e-1+t20.*sin(thk_b).*5.949652e-2;
et4 = t21.*sin(thk_f).*1.924852e-2-dl_b.*dtha_b.*t4.*(4.6e+1./1.25e+2)-dl_f.*dtha_f.*t5.*(4.6e+1./1.25e+2)+l_b.*t8.*t18.*(2.3e+1./1.25e+2)+l_f.*t9.*t19.*(2.3e+1./1.25e+2);
et5 = t16.*t22.*(-5.326992e-3)-t16.*t24.*1.67603873976e-2-t18.*t25.*1.318425768e-2+t21.*t26.*6.12102936e-3+t17.*t38.*8.555472e-3-t17.*t42.*2.69181979416e-2-t19.*t43.*2.117471688e-2+t20.*t44.*1.178031096e-2;
et6 = dl_b.*dtha_b.*t23.*7.2864e-2-dl_f.*dtha_f.*t39.*1.17024e-1-l_b.*t18.*t25.*3.6432e-2-l_f.*t19.*t43.*5.8512e-2;
mt1 = [et1+et2;et3+et4;et5+et6;t21.*t28.*(-4.65814184e-3)-t15.*t38.*8.555472e-3+t15.*t42.*2.69181979416e-2+t19.*t41.*2.53031208e-3-dl_f.*dtha_f.*t46.*1.3984e-2+l_f.*t19.*t41.*6.992e-3;t19.*(-2.157032e-2)-l_f.*t19.*(2.3e+1./1.25e+2)+t15.*t39.*5.8512e-2+t17.*t46.*6.992e-3];
mt2 = [t15.*t26.*6.12102936e-3-t17.*t28.*4.65814184e-3;dl_f.*dtha_f.*4.314064e-2+t15.*t43.*2.117471688e-2-t17.*t41.*2.53031208e-3+dl_f.*dtha_f.*l_f.*(4.6e+1./1.25e+2)+l_f.*t15.*t43.*5.8512e-2-l_f.*t17.*t41.*6.992e-3];
mt3 = [t15.*t22.*(-5.326992e-3)-t15.*t24.*1.67603873976e-2-t20.*t27.*1.439815784e-2+t18.*t40.*2.53031208e-3-dl_b.*dtha_b.*t45.*1.3984e-2+l_b.*t18.*t40.*6.992e-3;t18.*(-2.157032e-2)-l_b.*t18.*(2.3e+1./1.25e+2)+t15.*t23.*3.6432e-2+t16.*t45.*6.992e-3];
mt4 = [t16.*t27.*(-1.439815784e-2)-t15.*t44.*1.178031096e-2;dl_b.*dtha_b.*4.314064e-2-t15.*t25.*1.318425768e-2-t16.*t40.*2.53031208e-3+dl_b.*dtha_b.*l_b.*(4.6e+1./1.25e+2)-l_b.*t15.*t25.*3.6432e-2-l_b.*t16.*t40.*6.992e-3];
C = [mt1;mt2;mt3;mt4];
end
