function G = G_func(x,y,r,th_f,l_f,thk_f,tha_f,th_b,l_b,thk_b,tha_b)
%G_func
%    G = G_func(X,Y,R,TH_F,L_F,THK_F,THA_F,TH_B,L_B,THK_B,THA_B)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    19-Mar-2025 08:54:47

mt1 = [0.0;7.68498723e+1;cos(r).*5.103126050748759;cos(th_f).*(-8.30401011972e-1)+sin(th_f).*2.6392824e-1;sin(tha_f).*(-1.80504);cos(thk_f).*(-1.888279812e-1)];
mt2 = [cos(tha_f).*(l_f.*(2.3e+1./1.25e+2)+6.658716e-2).*(-9.81e+2./1.0e+2);cos(th_b).*(-8.30401011972e-1)+sin(th_b).*2.6392824e-1;sin(tha_b).*(-1.80504);cos(thk_b).*(-5.836608612e-1);cos(tha_b).*(l_b.*(2.3e+1./1.25e+2)+6.658716e-2).*(-9.81e+2./1.0e+2)];
G = [mt1;mt2];
end
