function Q = Q_func(x,y,r,th_f,l_f,thk_f,tha_f,th_b,l_b,thk_b,tha_b,t_f,f_f,t_b,f_b,grf_tf,grf_nf,grf_tb,grf_nb,f_endf,f_endb,f_cxf,f_cyf,f_cxb,f_cyb)
%Q_func
%    Q = Q_func(X,Y,R,TH_F,L_F,THK_F,THA_F,TH_B,L_B,THK_B,THA_B,T_F,F_F,T_B,F_B,GRF_TF,GRF_NF,GRF_TB,GRF_NB,F_ENDF,F_ENDB,F_CXF,F_CYF,F_CXB,F_CYB)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    19-Mar-2025 08:54:47

t2 = cos(r);
t3 = cos(th_b);
t4 = cos(th_f);
t5 = cos(tha_b);
t6 = cos(tha_f);
t7 = cos(thk_b);
t8 = cos(thk_f);
t9 = sin(r);
t10 = sin(th_b);
t11 = sin(th_f);
t12 = sin(tha_b);
t13 = sin(tha_f);
t14 = sin(thk_b);
t15 = sin(thk_f);
mt1 = [grf_tb+grf_tf;grf_nb+grf_nf;grf_nb.*t2.*(-9.9e+1./5.0e+2)+grf_nf.*t2.*(1.59e+2./5.0e+2)+grf_tb.*t9.*(9.9e+1./5.0e+2)-grf_tf.*t9.*(1.59e+2./5.0e+2);t_f-grf_nf.*t4.*(1.21e+2./5.0e+2)+grf_tf.*t11.*(1.21e+2./5.0e+2)-f_cxf.*(t4.*(1.9e+1./5.0e+2)-t11.*(1.21e+2./5.0e+2))-f_cyf.*(t4.*(1.21e+2./5.0e+2)+t11.*(1.9e+1./5.0e+2));f_f+f_endf+f_cxf.*t6+f_cyf.*t13;f_cyf.*t8.*(-5.7e+1./1.0e+3)-f_cxf.*t15.*(5.7e+1./1.0e+3)-grf_nf.*t8.*(1.17e+2./5.0e+2)-grf_tf.*t15.*(1.17e+2./5.0e+2);(l_f+1.1723e-1).*(f_cyf.*t6-f_cxf.*t13)];
mt2 = [t_b-grf_nb.*t3.*(1.21e+2./5.0e+2)-grf_tb.*t10.*(1.21e+2./5.0e+2)+f_cxb.*(t3.*(1.9e+1./5.0e+2)-t10.*(1.21e+2./5.0e+2))-f_cyb.*(t3.*(1.21e+2./5.0e+2)+t10.*(1.9e+1./5.0e+2));f_b+f_endb-f_cxb.*t5+f_cyb.*t12;f_cyb.*t7.*(-5.7e+1./1.0e+3)+f_cxb.*t14.*(5.7e+1./1.0e+3)-grf_nb.*t7.*(1.17e+2./5.0e+2)+grf_tb.*t14.*(1.17e+2./5.0e+2);(l_b+1.1723e-1).*(f_cyb.*t5+f_cxb.*t12)];
Q = [mt1;mt2];
end
