function out1 = H_func(x,y,r,th_f,l_f,thk_f,tha_f,th_b,l_b,thk_b,tha_b)
%H_func
%    OUT1 = H_func(X,Y,R,TH_F,L_F,THK_F,THA_F,TH_B,L_B,THK_B,THA_B)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    19-Mar-2025 08:54:47

t2 = cos(th_b);
t3 = cos(th_f);
t4 = cos(tha_b);
t5 = cos(tha_f);
t6 = sin(th_b);
t7 = sin(th_f);
t8 = sin(tha_b);
t9 = sin(tha_f);
t10 = l_b+2.21e+2./1.0e+3;
t11 = l_f+2.21e+2./1.0e+3;
mt1 = [0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,t3.*(-1.9e+1./5.0e+2)+t7.*(1.21e+2./5.0e+2),t3.*(-1.21e+2./5.0e+2)-t7.*(1.9e+1./5.0e+2),0.0,0.0,t5,t9,0.0,0.0,sin(thk_f).*(-5.7e+1./1.0e+3),cos(thk_f).*(-5.7e+1./1.0e+3),0.0,0.0,t9.*1.0377e-1-t9.*t11,t5.*(-1.0377e-1)+t5.*t11,0.0,0.0,0.0,0.0,t2.*(1.9e+1./5.0e+2)-t6.*(1.21e+2./5.0e+2),t2.*(-1.21e+2./5.0e+2)-t6.*(1.9e+1./5.0e+2),0.0,0.0,-t4,t8,0.0,0.0,sin(thk_b).*(5.7e+1./1.0e+3),cos(thk_b).*(-5.7e+1./1.0e+3),0.0,0.0];
mt2 = [t8.*(-1.0377e-1)+t8.*t10,t4.*(-1.0377e-1)+t4.*t10];
out1 = reshape([mt1,mt2],4,11);
end
