function phi_eqn = Q_Partial_func(r,th_f,thk_f,th_b,thk_b,t_f,f_f,t_b,f_b,grf_tf,grf_nf,grf_tb,grf_nb,f_endf,f_endb)
%Q_Partial_func
%    PHI_EQN = Q_Partial_func(R,TH_F,THK_F,TH_B,THK_B,T_F,F_F,T_B,F_B,GRF_TF,GRF_NF,GRF_TB,GRF_NB,F_ENDF,F_ENDB)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    19-Mar-2025 08:54:49

t2 = cos(r);
t3 = sin(r);
phi_eqn = [grf_tb+grf_tf;grf_nb+grf_nf;grf_nb.*t2.*(-9.9e+1./5.0e+2)+grf_nf.*t2.*(1.59e+2./5.0e+2)+grf_tb.*t3.*(9.9e+1./5.0e+2)-grf_tf.*t3.*(1.59e+2./5.0e+2);t_f-grf_nf.*cos(th_f).*(1.21e+2./5.0e+2)+grf_tf.*sin(th_f).*(1.21e+2./5.0e+2);f_f+f_endf;grf_nf.*cos(thk_f).*(-1.17e+2./5.0e+2)-grf_tf.*sin(thk_f).*(1.17e+2./5.0e+2);0.0;t_b-grf_nb.*cos(th_b).*(1.21e+2./5.0e+2)-grf_tb.*sin(th_b).*(1.21e+2./5.0e+2);f_b+f_endb;grf_nb.*cos(thk_b).*(-1.17e+2./5.0e+2)+grf_tb.*sin(thk_b).*(1.17e+2./5.0e+2);0.0];
end
