function dthk = dthk_calc(th,l,dth,dl)
%DTHK_CALC
%    DTHK = DTHK_CALC(TH,L,DTH,DL)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    19-Mar-2025 08:54:49

dthk = -dth+dl.*(l.*7.161773274254708e+1+1.58275189361029e+1).*1.0./sqrt(-((l+2.21e+2./1.0e+3).^2.*3.580886637127354e+1-2.26516146004765).^2+1.0);
end
