function th_function = th_calc(phi,l)
%TH_CALC
%    TH_FUNCTION = TH_CALC(PHI,L)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    19-Mar-2025 08:54:50

t2 = l+2.21e+2./1.0e+3;
t3 = t2.^2;
t4 = t3.*3.580886637127354e+1;
t5 = -t4;
t6 = t5+2.26516146004765;
t7 = acos(t6);
t8 = t7+1.557529807512923e-1;
th_function = phi-asin(sin(t8).*1.0./sqrt(cos(t8).*(-1.13256e-1)+1.1332e-1).*(1.17e+2./5.0e+2));
end
