function tha = tha_calc(th,l)
%THA_CALC
%    THA = THA_CALC(TH,L)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    19-Mar-2025 08:54:49

tha = th-pi./2.0+acos(((l+2.21e+2./1.0e+3).^2+5.6759e-2)./(l.*4.899306073312832e-1+1.082746642202136e-1))+1.415043346043604;
end
