function thk = thk_calc(th,l)
%THK_CALC
%    THK = THK_CALC(TH,L)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    19-Mar-2025 08:54:49

thk = -th+acos((l+2.21e+2./1.0e+3).^2.*(-3.580886637127354e+1)+2.26516146004765)+1.557529807512923e-1;
end
