function dr = dr_calc(th,l,dth,dl)
%DR_CALC
%    DR = DR_CALC(TH,L,DTH,DL)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    19-Mar-2025 08:54:49

t2 = l+2.21e+2./1.0e+3;
t3 = t2.^2;
t4 = t3.*3.580886637127354e+1;
t5 = -t4;
t6 = t5+2.26516146004765;
t7 = acos(t6);
t8 = t7+1.557529807512923e-1;
et1 = dl.*sin(t8).*(l.*7.161773274254708e+1+1.58275189361029e+1).*1.0./sqrt(-(t4-2.26516146004765).^2+1.0).*1.0./sqrt(cos(t8).*(-1.13256e-1)+1.1332e-1);
et2 = 5.6628e-2;
dr = et1.*et2;
end
