function r = r_calc(th,l)
%R_CALC
%    R = R_CALC(TH,L)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    19-Mar-2025 08:54:49

r = sqrt(cos(acos((l+2.21e+2./1.0e+3).^2.*(-3.580886637127354e+1)+2.26516146004765)+1.557529807512923e-1).*(-1.13256e-1)+1.1332e-1);
end
