function [x_foot,y_foot] = foot_pos_b(l_ps,theta_b,theta_m,x_body,y_body)
%FOOT_POS_B
%    [X_FOOT,Y_FOOT] = FOOT_POS_B(L_PS,THETA_B,THETA_M,X_BODY,Y_BODY)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    16-Aug-2024 13:26:00

t2 = l_ps+2.057e-1;
t3 = t2.^2;
t4 = t3.*4.269520124162065e+1;
t5 = -t4;
t6 = t5+2.639801597568163;
t7 = acos(t6);
t8 = t7+1.274053155386639e-1;
t9 = cos(t8);
t10 = sin(t8);
t11 = t9.*1.13256e-1;
t12 = -t11;
t13 = t12+1.1332e-1;
t14 = sqrt(t13);
t15 = 1.0./t14;
t16 = t10.*t15.*(1.17e+2./5.0e+2);
t17 = asin(t16);
t18 = -t17;
t19 = t18+theta_b+theta_m;
x_foot = x_body-cos(theta_b).*(2.61e+2./1.0e+3)+t14.*cos(t19);
if nargout > 1
    y_foot = y_body-sin(theta_b).*(2.61e+2./1.0e+3)+t14.*sin(t19);
end
end
