function [x_foot,y_foot] = foot_pos_f(l_ps,l_spine,theta_b,theta_m,x_body,y_body)
%FOOT_POS_F
%    [X_FOOT,Y_FOOT] = FOOT_POS_F(L_PS,L_SPINE,THETA_B,THETA_M,X_BODY,Y_BODY)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    16-Aug-2024 13:25:59

t2 = -theta_m;
t3 = l_spine+3.17e+2./1.0e+3;
t4 = l_ps+2.057e-1;
t5 = t4.^2;
t6 = t5.*4.269520124162065e+1;
t7 = -t6;
t8 = t7+2.639801597568163;
t9 = acos(t8);
t10 = t9+1.274053155386639e-1;
t11 = cos(t10);
t12 = sin(t10);
t13 = t11.*1.13256e-1;
t14 = -t13;
t15 = t14+1.1332e-1;
t16 = sqrt(t15);
t17 = 1.0./t16;
t18 = t12.*t17.*(1.17e+2./5.0e+2);
t19 = asin(t18);
t20 = t2+t19+theta_b;
x_foot = x_body-t16.*cos(t20)+t3.*cos(theta_b);
if nargout > 1
    y_foot = y_body-t16.*sin(t20)+t3.*sin(theta_b);
end
end
