function [x_hip,dx_hip,y_hip,dy_hip] = hip_pos_b(dtheta_b,dx_body,dy_body,theta_b,x_body,y_body)
%HIP_POS_B
%    [X_HIP,DX_HIP,Y_HIP,DY_HIP] = HIP_POS_B(DTHETA_B,DX_BODY,DY_BODY,THETA_B,X_BODY,Y_BODY)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    16-Aug-2024 13:26:00

t2 = cos(theta_b);
x_hip = t2.*(-2.61e+2./1.0e+3)+x_body;
if nargout > 1
    t3 = sin(theta_b);
    dx_hip = dx_body+dtheta_b.*t3.*(2.61e+2./1.0e+3);
end
if nargout > 2
    y_hip = t3.*(-2.61e+2./1.0e+3)+y_body;
end
if nargout > 3
    dy_hip = dy_body-dtheta_b.*t2.*(2.61e+2./1.0e+3);
end
end
