function [x_hip,dx_hip,y_hip,dy_hip] = hip_pos_f(dl_spine,dtheta_b,dx_body,dy_body,l_spine,theta_b,x_body,y_body)
%HIP_POS_F
%    [X_HIP,DX_HIP,Y_HIP,DY_HIP] = HIP_POS_F(DL_SPINE,DTHETA_B,DX_BODY,DY_BODY,L_SPINE,THETA_B,X_BODY,Y_BODY)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    16-Aug-2024 13:25:59

t2 = cos(theta_b);
t3 = sin(theta_b);
t4 = l_spine+3.17e+2./1.0e+3;
x_hip = x_body+t2.*t4;
if nargout > 1
    dx_hip = dl_spine+dx_body-dtheta_b.*t3.*t4;
end
if nargout > 2
    y_hip = y_body+t3.*t4;
end
if nargout > 3
    dy_hip = dl_spine+dy_body+dtheta_b.*t2.*t4;
end
end
