function F_s = f_1D(u_sym,t_sym,tau_sym,F_max_sym)
%f_1D
%    F_s = f_1D(U_SYM,T_SYM,TAU_SYM,F_max_sym)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    03-Nov-2025 11:54:57

t0 = roots([1.0,2.0e+3,1.666666666666666e+6,5.555555555555553e+8]);
et1 = sum(arrayfun(@(k) (exp(t_sym.*t0(k)).*t0(k).^2)./(t0(k).^2.*1.2884901888e+10+t0(k).*1.7179869184e+13+7.158278826666665e+15),1.0:3.0));
t2 = et1;
t0 = roots([1.0,2.0e+3,1.666666666666666e+6,5.555555555555553e+8]);
et2 = sum(arrayfun(@(k) exp(t_sym.*t0(k))./(t0(k).^2.*1.2884901888e+10+t0(k).*1.7179869184e+13+7.158278826666665e+15),1.0:3.0));
t3 = et2;
t0 = roots([1.0,2.0e+3,1.666666666666666e+6,5.555555555555553e+8]);
et3 = sum(arrayfun(@(k) (exp(t_sym.*t0(k)).*t0(k))./(t0(k).^2.*1.2884901888e+10+t0(k).*1.7179869184e+13+7.158278826666665e+15),1.0:3.0));
t4 = et3;
t5 = tau_sym.^2;
t6 = tau_sym.^3;
t7 = tau_sym.*8.589934592e+12;
t8 = t5.*7.158278826666665e+15;
t10 = t6.*2.386092942222221e+18;
t9 = -t8;
t11 = t7+t9+t10-4.294967296e+9;
t12 = 1.0./t11;
et4 = F_max_sym.*u_sym+t12.*(F_max_sym.*u_sym.*t2.*3.68934881474191e+19+F_max_sym.*u_sym.*t3.*6.148914691236516e+25+F_max_sym.*t2.*t5.*u_sym.*6.148914691236516e+25+F_max_sym.*t3.*t5.*u_sym.*1.024819115206086e+32+F_max_sym.*t4.*t5.*u_sym.*1.024819115206086e+29-F_max_sym.*tau_sym.*u_sym.*t3.*1.024819115206086e+29);
et5 = -F_max_sym.*t12.*u_sym.*exp(-t_sym./tau_sym).*(t7+t8+t10+4.294967296e+9);
F_s = et4+et5;
end
