function C = C_func(x,y,th,l,thk,tha,dx,dy,dth,dl,dthk,dtha)
%C_func
%    C = C_func(X,Y,TH,L,THK,THA,DX,DY,DTH,DL,DTHK,DTHA)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    03-Nov-2025 11:54:54

t2 = cos(th);
t3 = cos(tha);
t4 = sin(th);
t5 = sin(tha);
t6 = th+thk;
t7 = dth.^2;
t8 = dtha.^2;
t9 = dthk.^2;
t11 = -tha;
t10 = sin(t6);
t12 = t11+th;
t13 = cos(t12);
t14 = sin(t12);
mt1 = [-t7.*(t2.*8.46484212e-2-t4.*2.6904e-2)+t9.*cos(thk).*1.924852e-2-dtha.*(dl.*t5.*(2.3e+1./1.25e+2)+dtha.*t3.*(l.*(2.3e+1./1.25e+2)+7.1710088e-2))-dl.*dtha.*t5.*(2.3e+1./1.25e+2)];
mt2 = [t2.*t7.*2.6904e-2+t4.*t7.*8.46484212e-2+t5.*t8.*7.1710088e-2+t9.*sin(thk).*1.924852e-2-dl.*dtha.*t3.*(4.6e+1./1.25e+2)+l.*t5.*t8.*(2.3e+1./1.25e+2);t9.*t10.*(-4.65814184e-3)+t8.*t13.*2.724983344e-3-dl.*dtha.*t14.*1.3984e-2+l.*t8.*t13.*6.992e-3];
mt3 = [t8.*(-2.6693248e-2)-l.*t8.*(2.3e+1./1.25e+2)+t7.*t14.*6.992e-3;t7.*t10.*(-4.65814184e-3);dl.*dtha.*5.3386496e-2-t7.*t13.*2.724983344e-3+dl.*dtha.*l.*(4.6e+1./1.25e+2)-l.*t7.*t13.*6.992e-3];
C = [mt1;mt2;mt3];
end
