function out1 = dH_func(x,y,th,l,thk,tha,dx,dy,dth,dl,dthk,dtha)
%dH_func
%    OUT1 = dH_func(X,Y,TH,L,THK,THA,DX,DY,DTH,DL,DTHK,DTHA)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    03-Nov-2025 11:54:54

t2 = cos(th);
t3 = cos(tha);
t4 = sin(th);
t5 = sin(tha);
t6 = l+2.7e+1./1.25e+2;
out1 = reshape([0.0,0.0,0.0,0.0,-dth.*(t2.*(1.21e+2./5.0e+2)+t4.*(1.9e+1./5.0e+2)),-dth.*(t2.*(1.9e+1./5.0e+2)-t4.*(1.21e+2./5.0e+2)),dtha.*t5,dtha.*t3,dthk.*cos(thk).*(5.7e+1./1.0e+3),dthk.*sin(thk).*(5.7e+1./1.0e+3),dl.*t5+dtha.*t3.*t6,dl.*t3-dtha.*t5.*t6],[2,6]);
end
