function G = G_func(x,y,th,l,thk,tha)
%G_func
%    G = G_func(X,Y,TH,L,THK,THA)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    03-Nov-2025 11:54:54

mt1 = [0.0;3.692649927575e+1;cos(th).*(-8.3011743976098e-1)+sin(th).*2.638381116e-1];
mt2 = [sin(tha).*(-1.8044236);cos(thk).*(-1.88763498658e-1);cos(tha).*(l.*(2.3e+1./1.25e+2)+7.1710088e-2).*(-9.806649999999999)];
G = [mt1;mt2];
end
