function out1 = H_func(x,y,th,l,thk,tha)
%H_func
%    OUT1 = H_func(X,Y,TH,L,THK,THA)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    03-Nov-2025 11:54:54

t2 = cos(th);
t3 = cos(tha);
t4 = sin(th);
t5 = sin(tha);
t6 = l+2.7e+1./1.25e+2;
out1 = reshape([0.0,0.0,0.0,0.0,t2.*(1.9e+1./5.0e+2)-t4.*(1.21e+2./5.0e+2),t2.*(-1.21e+2./5.0e+2)-t4.*(1.9e+1./5.0e+2),-t3,t5,sin(thk).*(5.7e+1./1.0e+3),cos(thk).*(-5.7e+1./1.0e+3),t5.*t6,t3.*t6],[2,6]);
end
