function M = M_func(x,y,th,l,thk,tha)
%M_func
%    M = M_func(X,Y,TH,L,THK,THA)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    03-Nov-2025 11:54:53

t2 = cos(th);
t3 = cos(tha);
t4 = cos(thk);
t5 = sin(th);
t6 = sin(tha);
t7 = sin(thk);
t8 = th+thk;
t10 = -tha;
t14 = l.*(2.3e+1./1.25e+2);
t18 = l.*2.3e+7;
t9 = cos(t8);
t11 = t10+th;
t15 = t3.*(2.3e+1./1.25e+2);
t16 = t6.*(2.3e+1./1.25e+2);
t19 = t2.*2.6904e-2;
t20 = t5.*2.6904e-2;
t23 = t4.*1.924852e-2;
t24 = t7.*1.924852e-2;
t26 = t18+8.963761e+6;
t28 = t2.*8.46484212e-2;
t29 = t5.*8.46484212e-2;
t33 = t14+7.1710088e-2;
t12 = cos(t11);
t13 = sin(t11);
t17 = -t16;
t21 = -t19;
t27 = -t23;
t30 = -t28;
t31 = -t29;
t32 = t9.*4.65814184e-3;
t34 = t3.*t33;
t35 = t6.*t33;
t22 = t12.*6.992e-3;
t36 = -t34;
t37 = -t35;
t38 = t20+t30;
t39 = t21+t31;
t40 = t13.*t26.*3.04e-10;
t25 = -t22;
t41 = -t40;
mt1 = [3.765455,0.0,t39,t15,t24,t37,0.0,3.765455,t38,t17,t27,t36,t39,t38,2.3543569020848e-2,t25,t32,t41,t15,t17,t25,2.3e+1./1.25e+2,0.0,0.0,t24,t27,t32,0.0];
mt2 = [7.9756744064e-3,0.0,t37,t36,t41,0.0,0.0,l.*5.3386496e-2+l.*t14+1.5153833690512e-2];
M = reshape([mt1,mt2],6,6);
end
