function Q = Q_func(x,y,th,l,thk,tha,t,f,grf_t,grf_n,f_end,f_cx,f_cy,dy)
%Q_func
%    Q = Q_func(X,Y,TH,L,THK,THA,T,F,GRF_T,GRF_N,F_END,F_CX,F_CY,DY)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    03-Nov-2025 11:54:54

t2 = cos(th);
t3 = cos(tha);
t4 = cos(thk);
t5 = sin(th);
t6 = sin(tha);
t7 = sin(thk);
t8 = y.*(4.0e+1./1.03e+2);
t9 = t8-3.922330097087379e-2;
t10 = t9.^2;
et1 = grf_n+t10.*4.767653474418777e+1-(dy.^2.*t9.*1.702182524271845)./(t10-1.0);
et2 = -4.692810996187765;
Q = [grf_t;et1+et2;t-grf_n.*t2.*(1.21e+2./5.0e+2)-grf_t.*t5.*(1.21e+2./5.0e+2)+f_cx.*(t2.*(1.9e+1./5.0e+2)-t5.*(1.21e+2./5.0e+2))-f_cy.*(t2.*(1.21e+2./5.0e+2)+t5.*(1.9e+1./5.0e+2));f+f_end-f_cx.*t3+f_cy.*t6;f_cy.*t4.*(-5.7e+1./1.0e+3)+f_cx.*t7.*(5.7e+1./1.0e+3)-grf_n.*t4.*(1.17e+2./5.0e+2)+grf_t.*t7.*(1.17e+2./5.0e+2);(l+2.7e+1./1.25e+2).*(f_cy.*t3+f_cx.*t6)];
end
