function out1 = Q_grf_func(th,thk,grf_t,grf_n)
%Q_grf_func
%    OUT1 = Q_grf_func(TH,THK,GRF_T,GRF_N)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    06-Mar-2025 09:06:00

out1 = [grf_t;grf_n;grf_n.*cos(th).*(-1.21e+2./5.0e+2)+grf_t.*sin(th).*(1.21e+2./5.0e+2);0.0;grf_n.*cos(thk).*(-1.17e+2./5.0e+2)-grf_t.*sin(thk).*(1.17e+2./5.0e+2);0.0];
end
