function phi_eqn = Q_Partial_func(th,thk,t,f,grf_t,grf_n,f_end,y,dy)
%Q_Partial_func
%    PHI_EQN = Q_Partial_func(TH,THK,T,F,GRF_T,GRF_N,F_END,Y,DY)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    03-Nov-2025 11:54:55

t2 = y.*(4.0e+1./1.03e+2);
t3 = t2-3.922330097087379e-2;
t4 = t3.^2;
et1 = grf_n+t4.*4.767653474418777e+1-(dy.^2.*t3.*1.702182524271845)./(t4-1.0);
et2 = -4.692810996187765;
phi_eqn = [grf_t;et1+et2;t-grf_n.*cos(th).*(1.21e+2./5.0e+2)-grf_t.*sin(th).*(1.21e+2./5.0e+2);f+f_end;grf_n.*cos(thk).*(-1.17e+2./5.0e+2)+grf_t.*sin(thk).*(1.17e+2./5.0e+2);0.0];
end
