function dphi = dx_to_dphi(dx,phi,r,dr)
%DX_TO_DPHI
%    DPHI = DX_TO_DPHI(DX,PHI,R,DR)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    06-Mar-2025 09:54:52

dphi = -(dx-dr.*cos(phi))./(r.*sin(phi));
end
