function hip_matrix = foot_to_hip(x_foot,y_foot,th,l)
%FOOT_TO_HIP
%    HIP_MATRIX = FOOT_TO_HIP(X_FOOT,Y_FOOT,TH,L)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    06-Mar-2025 09:54:52

t2 = -th;
t3 = l+5.1e+1./2.5e+2;
t4 = t3.^2;
t5 = t4.*4.269520124162065e+1;
t6 = -t5;
t7 = t6+2.639801597568163;
t8 = acos(t7);
t9 = t2+t8+1.274053155386639e-1;
hip_matrix = [x_foot-cos(t9).*(1.17e+2./5.0e+2)+cos(th).*(1.21e+2./5.0e+2)-2.61e+2./1.0e+3;y_foot+sin(t9).*(1.17e+2./5.0e+2)+sin(th).*(1.21e+2./5.0e+2)];
end
