function phi_function = phi_calc(th,l)
%PHI_CALC
%    PHI_FUNCTION = PHI_CALC(TH,L)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    03-Nov-2025 11:54:56

t2 = l+2.7e+1./1.25e+2;
t3 = t2.^2;
t4 = t3.*3.580886637127354e+1;
t5 = -t4;
t6 = t5+2.26516146004765;
t7 = acos(t6);
t8 = t7+1.557529807512923e-1;
phi_function = th+asin(sin(t8).*1.0./sqrt(cos(t8).*(-1.13256e-1)+1.1332e-1).*(1.17e+2./5.0e+2));
end
