function r = r_calc(th,l)
%R_CALC
%    R = R_CALC(TH,L)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    03-Nov-2025 11:54:56

r = sqrt(cos(acos((l+2.7e+1./1.25e+2).^2.*(-3.580886637127354e+1)+2.26516146004765)+1.557529807512923e-1).*(-1.13256e-1)+1.1332e-1)+1.0./5.0e+1;
end
